CREATE DATABASE Primitiva

GO

CREATE TABLE Sorteos
(
	Fecha DATE NOT NULL,
	Reintegro TINYINT NOT NULL,
	Complementario TINYINT NOT NULL,
	Numero1 TINYINT NOT NULL,
	Numero2 TINYINT NOT NULL,
	Numero3 TINYINT NOT NULL,
	Numero4 TINYINT NOT NULL,
	Numero5 TINYINT NOT NULL,
	Numero6 TINYINT NOT NULL,

	CONSTRAINT PK_Sorteos PRIMARY KEY (Fecha)
)

GO

CREATE TABLE Boletos
(
	ID UNIQUEIDENTIFIER NOT NULL,
	FechaSorteo DATE NOT NULL,
	Reintegro TINYINT NOT NULL,


	CONSTRAINT PK_Boletos PRIMARY KEY (ID),
	CONSTRAINT FK_Boletos_Sorteos FOREIGN KEY (FechaSorteo) REFERENCES Sorteos (Fecha) ON UPDATE CASCADE ON DELETE NO ACTION

)

GO

CREATE TABLE Apuestas
(
	ID UNIQUEIDENTIFIER NOT NULL,
	ID_Boleto UNIQUEIDENTIFIER NOT NULL,
	Tipo BIT NOT NULL,

	CONSTRAINT PK_Apuestas PRIMARY KEY (ID),
	CONSTRAINT FK_Apuestas_Boletos FOREIGN KEY (ID_Boleto) REFERENCES Boletos (ID) ON UPDATE CASCADE ON DELETE CASCADE
)

GO

CREATE TABLE Numeros
(
	Valor TINYINT NOT NULL,
	IDApuesta UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT PK_Numeros PRIMARY KEY (Valor),
	CONSTRAINT FK_Numeros_Apuestas FOREIGN KEY (IDApuesta) REFERENCES Apuestas (ID) ON UPDATE CASCADE ON DELETE CASCADE
)

GO