CREATE DATABASE Primitiva

GO

CREATE TABLE Sorteos
(
	Fecha DATE NOT NULL,

	CONSTRAINT PK_Sorteos PRIMARY KEY (Fecha)
)

GO

CREATE TABLE Boletos
(
	ID UNIQUEIDENTIFIER NOT NULL,
	FechaSorteo DATE NOT NULL,

	CONSTRAINT PK_Boletos PRIMARY KEY (ID),
	CONSTRAINT FK_Boletos_Sorteos FOREIGN KEY (FechaSorteo) REFERENCES Sorteos (Fecha) ON UPDATE CASCADE ON DELETE NO ACTION

)

GO

CREATE TABLE Apuestas
(
	ID UNIQUEIDENTIFIER NOT NULL,
	ID_Boleto UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT PK_Apuestas PRIMARY KEY (ID),
	CONSTRAINT FK_Apuestas_Boletos FOREIGN KEY (ID_Boleto) REFERENCES Boletos (ID) ON UPDATE CASCADE ON DELETE NO ACTION
)

CREATE TABLE Apuestas_Simple
(
	
)

GO